[project]
name = 'InsurancePool'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.auditor-rewards]
path = 'contracts/auditor-rewards.clar'
clarity_version = 2
epoch = 2.5

[contracts.claims]
path = 'contracts/claims.clar'
clarity_version = 2
epoch = 2.5

[contracts.insurance-pool]
path = 'contracts/insurance-pool.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
